package com.example.dome2;

public enum TYPES {
    FINDCDKS,CDKINFO,FINDORDERS,ORDERINFO,FINDPIFUS,PIFUINFO,FINDZHOUBIANS,ZHOUBIANINFO,FINDSALES,SALEINFO,FINDPLAYERS,PLAYERINFO,ADDORDER,ADDSALE,DELETESALE;
}
